In [1]:
import numpy as np

In [2]:
arr = np.array([4,3,2,4,6,6.2,9,2,7,4,9])

In [3]:
arr

array([4. , 3. , 2. , 4. , 6. , 6.2, 9. , 2. , 7. , 4. , 9. ])

In [4]:
np.sort(arr)

array([2. , 2. , 3. , 4. , 4. , 4. , 6. , 6.2, 7. , 9. , 9. ])

In [5]:
np.searchsorted(arr, 34)

11

In [6]:
arr1 = np.array([0,345,454,0,0,0,0])

In [7]:
np.count_nonzero(arr1)

2

In [8]:
arr

array([4. , 3. , 2. , 4. , 6. , 6.2, 9. , 2. , 7. , 4. , 9. ])

In [9]:
np.where(arr>6)

(array([ 5,  6,  8, 10]),)

In [10]:
np.extract(arr>3, arr)

NameError: name 'atrr' is not defined

In [11]:
arr

array([4. , 3. , 2. , 4. , 6. , 6.2, 9. , 2. , 7. , 4. , 9. ])

In [12]:
a=np.copy(arr)

In [13]:
import numpy.matlib as nm

In [15]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [16]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])