In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))

In [3]:
arr

array([[7, 1, 5, 5],
       [9, 7, 6, 1],
       [1, 2, 9, 7]])

In [4]:
arr.reshape(2,6)

array([[7, 1, 5, 5, 9, 7],
       [6, 1, 1, 2, 9, 7]])

In [5]:
arr.reshape(2,-122)

array([[7, 1, 5, 5, 9, 7],
       [6, 1, 1, 2, 9, 7]])

In [6]:
arr

array([[7, 1, 5, 5],
       [9, 7, 6, 1],
       [1, 2, 9, 7]])

In [7]:
arr.T

array([[7, 9, 1],
       [1, 7, 2],
       [5, 6, 9],
       [5, 1, 7]])

In [8]:
arr

array([[7, 1, 5, 5],
       [9, 7, 6, 1],
       [1, 2, 9, 7]])

In [9]:
arr.flatten()

array([7, 1, 5, 5, 9, 7, 6, 1, 1, 2, 9, 7])

In [10]:
arr1= np.array([1,2,3,4])

In [11]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [14]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4]])

In [15]:
np.squeeze(arr)

array([[7, 1, 5, 5],
       [9, 7, 6, 1],
       [1, 2, 9, 7]])

In [16]:
data = np.array([[1],[2],[3]])

In [17]:
np.squeeze(data)

array([1, 2, 3])

In [18]:
arr1

array([1, 2, 3, 4])

In [19]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [20]:
np.roll(arr1, 2)

array([3, 4, 1, 2])