In [40]:
import numpy as np

In [41]:
l=[1,2,3,4]

In [42]:
ar=np.array(l)

In [43]:
ar

array([1, 2, 3, 4])

In [44]:
type(ar)

numpy.ndarray

In [45]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [46]:
np.asarray(l)

array([1, 2, 3, 4])

In [47]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [48]:
a=[2,3,4]

In [49]:
np.asarray(a)

array([2, 3, 4])

In [50]:
b=np.matrix(l)

In [51]:
b

matrix([[1, 2, 3, 4]])

In [52]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [53]:
a=np.array([1,2,3,4])

In [54]:
a

array([1, 2, 3, 4])

In [55]:
c=a

In [56]:
c

array([1, 2, 3, 4])

In [57]:
a

array([1, 2, 3, 4])

In [58]:
c[0]=100

In [59]:
c

array([100,   2,   3,   4])

In [60]:
a

array([100,   2,   3,   4])

In [61]:
#with change in c values inside a will also change
because a and c vales are kept inside one
place so change in any will effect

SyntaxError: invalid syntax (4118275167.py, line 2)

In [62]:
d=np.copy(a)

In [63]:
d

array([100,   2,   3,   4])

In [64]:
a

array([100,   2,   3,   4])

In [65]:
a[1]=200

In [66]:
a

array([100, 200,   3,   4])

In [67]:
d

array([100,   2,   3,   4])

In [68]:
#d wil not change with a as a and d have both data at different locations

In [69]:
    np.fromfunction(lambda i,j:i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [70]:
    np.fromfunction(lambda i,j:i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [71]:
iterable = (i*i for i in range(5))

In [72]:
np.fromiter(iterable,float) #used to make array

array([ 0.,  1.,  4.,  9., 16.])

In [73]:
np.fromstring('234 234', sep=' ')    #converted 234 234 into array of [234 234]

array([234., 234.])

In [74]:
np.fromstring('234,234', sep=',')

array([234., 234.])

In [75]:
l=[2,3,4,5,6]

In [78]:
ar = np.array(l)

In [79]:
ar

array([2, 3, 4, 5, 6])

In [80]:
ar.ndim

1

In [81]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])

In [82]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [83]:
ar2.ndim

2

In [84]:
ar2.size

8

In [85]:
ar.size

5

In [86]:
ar.shape

(5,)

In [87]:
ar2.shape

(2, 4)

In [88]:
ar.dtype

dtype('int64')

In [90]:
ar.dtype

dtype('int64')

In [91]:
ar2.dtype

dtype('int64')

In [92]:
ar22 = np.array([(1.4,45,45) , (23,45,66)])

In [94]:
ar22.dtype

dtype('float64')

In [95]:
list(range(5))

[0, 1, 2, 3, 4]

In [98]:
list(range(2.3,5.6))

TypeError: 'float' object cannot be interpreted as an integer

In [100]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [101]:
list(np.arange(2.3,5.6))

[2.3, 3.3, 4.3, 5.3]

In [102]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [104]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [105]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [107]:
np.zeros((3,4,2))   #3 layers and 4x2

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [108]:
ar4= np.zeros((3,4,5,6))

In [109]:
ar4.ndim

4

In [110]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [111]:
np.ones(5)+2

array([3., 3., 3., 3., 3.])

In [113]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [115]:
np.empty((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [116]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [117]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [119]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [120]:
np.logspace(2,5,10)    #base 10

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [121]:
np.logspace(2,5,10,  base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [123]:
arr=np.random.randn(3,4)  #mean 0 and SD=1

In [125]:
import pandas as pd

In [126]:
pd.DataFrame(arr)

0         1         2         3
0  0.150494  1.904117  0.361703 -0.163233
1  0.822322 -0.673774  1.126875  0.627767
2  1.518787 -0.677569  0.716159 -1.167266

In [127]:
np.random.rand(3,4)

array([[0.8832858 , 0.96429453, 0.82459801, 0.92445901],
       [0.2713618 , 0.10180283, 0.27979565, 0.82919567],
       [0.6246976 , 0.21831068, 0.20098747, 0.89121872]])

In [131]:
pd.DataFrame(np.random.randint(1,110,(50,50))).to_csv('test.csv')

In [132]:
arr=np.random.rand(3,4)

In [133]:
arr

array([[0.77201967, 0.91519266, 0.05256992, 0.83208099],
       [0.24107267, 0.92856554, 0.94540761, 0.32902299],
       [0.02718586, 0.53359882, 0.11352326, 0.22720637]])

In [137]:
arr.reshape(6,2)

array([[0.77201967, 0.91519266],
       [0.05256992, 0.83208099],
       [0.24107267, 0.92856554],
       [0.94540761, 0.32902299],
       [0.02718586, 0.53359882],
       [0.11352326, 0.22720637]])

In [139]:
arr[1][1]

0.9285655381023694

In [142]:
arr1=np.random.rand(5,3)

In [143]:
arr1

array([[0.63112668, 0.42112917, 0.16251273],
       [0.04632998, 0.19820732, 0.33324195],
       [0.21830136, 0.05222152, 0.02208667],
       [0.94613805, 0.90118145, 0.50200522],
       [0.8174519 , 0.5548435 , 0.60998926]])

In [144]:
arr1[0:3]

array([[0.63112668, 0.42112917, 0.16251273],
       [0.04632998, 0.19820732, 0.33324195],
       [0.21830136, 0.05222152, 0.02208667]])

In [146]:
arr1[0:3:1]

array([[0.63112668, 0.42112917, 0.16251273],
       [0.04632998, 0.19820732, 0.33324195],
       [0.21830136, 0.05222152, 0.02208667]])

In [149]:
arr=np.random.randint(1,100,(5,5))

In [150]:
arr>50

array([[False,  True, False,  True,  True],
       [ True, False, False,  True,  True],
       [ True,  True, False, False,  True],
       [False,  True,  True, False, False],
       [ True, False, False, False,  True]])

In [151]:
arr[arr>50]

array([69, 62, 97, 72, 84, 80, 84, 85, 87, 81, 60, 79, 65])

In [152]:
arr

array([[43, 69, 31, 62, 97],
       [72, 17, 46, 84, 80],
       [84, 85, 11, 15, 87],
       [43, 81, 60, 16, 33],
       [79, 42, 11, 41, 65]])

In [154]:
arr[2:4, [1,2]]

array([[85, 11],
       [81, 60]])

In [155]:
arr[0][0]=5000

In [156]:
arr

array([[5000,   69,   31,   62,   97],
       [  72,   17,   46,   84,   80],
       [  84,   85,   11,   15,   87],
       [  43,   81,   60,   16,   33],
       [  79,   42,   11,   41,   65]])

In [160]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))


In [161]:
arr1

array([[2, 2, 1],
       [1, 1, 1],
       [1, 2, 1]])

In [162]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [163]:
arr1+arr2

array([[4, 4, 2],
       [3, 2, 2],
       [3, 3, 2]])

In [164]:
arr1/arr2

array([[1. , 1. , 1. ],
       [0.5, 1. , 1. ],
       [0.5, 2. , 1. ]])

In [166]:
arr1*arr2

array([[4, 4, 1],
       [2, 1, 1],
       [2, 2, 1]])

In [167]:
arr1@arr2   #matrix multiplication

array([[10,  7,  5],
       [ 6,  4,  3],
       [ 8,  5,  4]])

In [168]:
arr1/0

/tmp/ipykernel_22918/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [169]:
arr1+100

array([[102, 102, 101],
       [101, 101, 101],
       [101, 102, 101]])

In [170]:
arr1**2

array([[4, 4, 1],
       [1, 1, 1],
       [1, 4, 1]])

In [188]:
arr=np.zeros((5,5))

In [189]:
row=np.array([1,2,3,4,5])

In [190]:
arr+row

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [191]:
row.T

array([1, 2, 3, 4, 5])